final List<Map<String, dynamic>> levels = [
  {'word': 'FLUTTER', 'hint': 'Framework populaire'},
  {'word': 'DART', 'hint': 'Langage de programmation'},
  {'word': 'CODE', 'hint': 'Ce que les devs écrivent'},
  {'word': 'EMILIEN', 'hint': 'Les 12 coups de midi'},
  {'word': 'HISTOIRE', 'hint': 'Tu racontes des ...'},
  {'word': 'ANDROID', 'hint': 'Système d\'exploitation mobile'},
  {'word': 'WIDGET', 'hint': 'Composant UI dans Flutter'},
  {'word': 'FIREBASE', 'hint': 'Backend proposé par Google'},
  {'word': 'GOOGLE', 'hint': 'Créateur de Flutter'},
  {'word': 'VARIABLE', 'hint': 'Contient une valeur modifiable'},
  {'word': 'FONCTION', 'hint': 'Tu l\'appelles avec des parenthèses'},
  {'word': 'CLASSE', 'hint': 'Modèle pour créer des objets'},
  {'word': 'NAVIGATOR', 'hint': 'Permet de changer de page dans Flutter'},
  {
    'word': 'ASYNC',
    'hint': 'Mot-clé pour exécuter du code de manière non bloquante',
  },
  {'word': 'STATE', 'hint': 'Ce que tu gères avec setState()'},
  {'word': 'DEBUG', 'hint': 'Étape pour corriger les erreurs'},
  {'word': 'ERROR', 'hint': 'Ce que tu obtiens quand ça plante'},
  {'word': 'LOADING', 'hint': 'Ce qui s\'affiche pendant un fetch'},
  {'word': 'GITHUB', 'hint': 'Héberge ton code et tes projets'},
  {'word': 'BRANCH', 'hint': 'Une version parallèle dans Git'},
  {'word': 'MERGE', 'hint': 'Tu lances ça pour combiner deux branches'},
  {'word': 'PULL', 'hint': 'Tu fais ça avant de coder à plusieurs'},
  {'word': 'PUSH', 'hint': 'Tu fais ça pour envoyer ton code'},
  {'word': 'REACT', 'hint': 'Une autre bibliothèque frontend très populaire'},
  {'word': 'HTML', 'hint': 'Langage de base pour les pages web'},
  {'word': 'CSS', 'hint': 'Fait le style de tes pages'},
  {'word': 'JAVASCRIPT', 'hint': 'Langage client du web'},
  {'word': 'PYTHON', 'hint': 'Langage souvent utilisé pour l\'IA'},
  {'word': 'ALGORITHME', 'hint': 'Enchaînement d\'instructions logiques'},
  {'word': 'STAGE', 'hint': 'Ce que tu dois faire en entreprise'},
  {'word': 'PROJET', 'hint': 'Travail à rendre en fin de semestre'},
  {'word': 'EXAMEN', 'hint': 'Ça arrive en fin de période'},
  {'word': 'ETUDIANT', 'hint': 'Celui qui apprend'},
  {'word': 'PROFESSEUR', 'hint': 'Celui qui enseigne'},
  {'word': 'TABLEAU', 'hint': 'Contient plusieurs éléments dans une liste'},
  {'word': 'INT', 'hint': 'Type de variable pour un nombre entier'},
  {'word': 'STRING', 'hint': 'Type pour une chaîne de caractères'},
  {'word': 'BOOLEAN', 'hint': 'true ou false'},
  {'word': 'CONSOLE', 'hint': 'Où s\'affichent les print()'},
  {'word': 'LOOP', 'hint': 'Pour répéter du code plusieurs fois'},
  {'word': 'IF', 'hint': 'Condition de base'},
  {'word': 'ELSE', 'hint': 'Sinon...'},
  {'word': 'RETURN', 'hint': 'Sort d\'une fonction et renvoie une valeur'},
  {'word': 'IMPORT', 'hint': 'Tu le fais pour utiliser un autre fichier'},
  {'word': 'PACKAGE', 'hint': 'Ensemble de fonctionnalités prêtes à l\'emploi'},
  {'word': 'API', 'hint': 'Permet à deux systèmes de communiquer'},
  {'word': 'JSON', 'hint': 'Format d\'échange de données très courant'},
  {'word': 'SERVER', 'hint': 'Ce qui traite les requêtes'},
  {'word': 'CLIENT', 'hint': 'C\'est toi ou ton app'},
  {'word': 'LOGIN', 'hint': 'Ce que tu fais pour accéder à ton compte'},
  {'word': 'PASSWORD', 'hint': 'Ce que tu ne dois jamais partager'},
  {'word': 'SECURITE', 'hint': 'Très important pour les données'},
];
